[package]
name = "as_derive"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "1.0", features=["extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true
